/* eslint-disable max-len */
export const challenge = '123456789';
export const vc_jwt = 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvbnMvY3JlZGVudGlhbHMvdjIiLCJodHRwczovL3d3dy53My5vcmcvbnMvY3JlZGVudGlhbHMvZXhhbXBsZXMvdjIiXSwiaWQiOiJodHRwOi8vZXhhbXBsZS5lZHUvY3JlZGVudGlhbHMvMzczMiIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJVbml2ZXJzaXR5RGVncmVlQ3JlZGVudGlhbCJdLCJpc3N1ZXIiOiJodHRwczovL2V4YW1wbGUuZWR1L2lzc3VlcnMvNTY1MDQ5IiwidmFsaWRGcm9tIjoiMjAxMC0wMS0wMVQwMDowMDowMFoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDpleGFtcGxlOmViZmViMWY3MTJlYmM2ZjFjMjc2ZTEyZWMyMSIsImRlZ3JlZSI6eyJ0eXBlIjoiQmFjaGVsb3JEZWdyZWUiLCJuYW1lIjoiQmFjaGVsb3Igb2YgU2NpZW5jZSBhbmQgQXJ0cyJ9fX0sImlzcyI6Imh0dHBzOi8vZXhhbXBsZS5lZHUvaXNzdWVycy81NjUwNDkiLCJqdGkiOiJodHRwOi8vZXhhbXBsZS5lZHUvY3JlZGVudGlhbHMvMzczMiIsInN1YiI6ImRpZDpleGFtcGxlOmViZmViMWY3MTJlYmM2ZjFjMjc2ZTEyZWMyMSJ9.0fkQPZOKlD0Sl0A798KBUNMOdGq90McQQIEtKU9tgSd9K1kRcxWVKDXQJcn_FJqLvo2bk793EHk-RTeEL1HyAQ';
export const vp_jwt = 'eyJ0eXAiOiAiSldUIiwgImFsZyI6ICJFZERTQSIsICJraWQiOiAiZGlkOmtleTp6Nk1rajhoM2t6V1pyUGl1Y295WTlMR0NUcFhoQ3FCb1gzZG9EbUh6NU1hUHhudmkjejZNa2o4aDNreldaclBpdWNveVk5TEdDVHBYaENxQm9YM2RvRG1IejVNYVB4bnZpIn0.eyJpc3MiOiAiZGlkOmtleTp6Nk1rajhoM2t6V1pyUGl1Y295WTlMR0NUcFhoQ3FCb1gzZG9EbUh6NU1hUHhudmkiLCAiYXVkIjogImV4YW1wbGUuY29tIiwgIm5vbmNlIjogIjEyMzQ1Njc4OSIsICJ2cCI6IHsiQGNvbnRleHQiOiBbImh0dHBzOi8vd3d3LnczLm9yZy9ucy9jcmVkZW50aWFscy92MiJdLCAidHlwZSI6IFsiVmVyaWZpYWJsZVByZXNlbnRhdGlvbiJdLCAiaG9sZGVyIjogImRpZDprZXk6ejZNa2o4aDNreldaclBpdWNveVk5TEdDVHBYaENxQm9YM2RvRG1IejVNYVB4bnZpIiwgInZlcmlmaWFibGVDcmVkZW50aWFsIjogW3siQGNvbnRleHQiOiAiaHR0cHM6Ly93d3cudzMub3JnL25zL2NyZWRlbnRpYWxzL3YyIiwgInR5cGUiOiAiRW52ZWxvcGVkVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCAiaWQiOiAiZGF0YTphcHBsaWNhdGlvbi9qd3QsZXlKaGJHY2lPaUpGVXpJMU5pSXNJbXRwWkNJNkltUnBaRHByWlhrNmVrUnVZV1ZVVVV0RVlsaFJWRFJpWVhSNFMyTnVUVkZaVVRoS2VXNXFjVU0xV0hveGRVMXJOV1YxUnpKb2REaHVjU042Ukc1aFpWUlJTMFJpV0ZGVU5HSmhkSGhMWTI1TlVWbFJPRXA1Ym1weFF6VlllakYxVFdzMVpYVkhNbWgwT0c1eEluMC5leUpwYzNNaU9pSmthV1E2YTJWNU9ucEVibUZsVkZGTFJHSllVVlEwWW1GMGVFdGpiazFSV1ZFNFNubHVhbkZETlZoNk1YVk5helZsZFVjeWFIUTRibkVpTENKemRXSWlPaUprYVdRNlpYaGhiWEJzWlRwaGJHbGpaU0lzSW5aaklqcDdJa0JqYjI1MFpYaDBJanBiSW1oMGRIQnpPaTh2ZDNkM0xuY3pMbTl5Wnk5dWN5OWpjbVZrWlc1MGFXRnNjeTkyTWlKZExDSjBlWEJsSWpwYklsWmxjbWxtYVdGaWJHVkRjbVZrWlc1MGFXRnNJbDBzSW1OeVpXUmxiblJwWVd4VGRXSnFaV04wSWpwN0ltbGtJam9pWkdsa09tVjRZVzF3YkdVNllXeHBZMlVpTENKdVlXMWxJam9pUVd4cFkyVWlmU3dpYVhOemRXVnlJam9pWkdsa09tdGxlVHA2Ukc1aFpWUlJTMFJpV0ZGVU5HSmhkSGhMWTI1TlVWbFJPRXA1Ym1weFF6VlllakYxVFdzMVpYVkhNbWgwT0c1eEluMTkucUU4VVliU0pmSWRZVV9MU3d4TEVJRHRqVHBMTGFwNkVZNTNKR3dhZy1UM3dyX2FROVNRem1pcUZFMUZQWEZnZkFVOEdIT2tTWTdBUm1feDVBRnZPTkEifV19fQ.9L0gNj8NbDTMZhCCNDL-q6aSKEddxuJKsX0FGGb7qooHsQQ7i_ZHQEo3hL2jzowWvHzrX4PGTrAhc8j4SIkFCg';
export const credential = {
  '@context': ['https://www.w3.org/ns/credentials/v2'],
  type: ['VerifiableCredential'],
  credentialSubject: {
    name: 'Alice'
  }
};
export const envelopedCredential = {
  '@context': 'https://www.w3.org/ns/credentials/v2',
  type: 'EnvelopedVerifiableCredential',
  id: `data:application/vc+jwt,${vc_jwt}`
};
export const presentation = {
  '@context': ['https://www.w3.org/ns/credentials/v2'],
  type: ['VerifiablePresentation']
};
export const envelopedPresentation = {
  '@context': 'https://www.w3.org/ns/credentials/v2',
  type: 'EnvelopedVerifiablePresentation',
  id: `data:application/vp+jwt,${vp_jwt}`
};
export const relatedResource = {
  id: 'https://www.w3.org/ns/credentials/v2',
  mediaType: 'application/ld+json',
  digestSRI: 'sha384-NSOcNpmdIVUxIJGvGUoe22FjTWrXiaXlsZ8q6912LdnR3KraQO2n75Ica4wK4Qeg',
  digestMultibase: 'uJKGMkOmFbVJhEfKTduMC2XCyvRAYLjOVmZWwIH1wQ7k',
};
